import oracledb

# Configurações de conexão (Ajuste com seus dados)
USUARIO = "seu_usuario"
SENHA = "sua_senha"
DSN = "localhost:1521/xe" # Host:Porta/Serviço

def conectar():
    try:
        return oracledb.connect(user=USUARIO, password=SENHA, dsn=DSN)
    except Exception as e:
        print(f"Erro ao conectar no Oracle: {e}")
        return None

def criar_tabela():
    conn = conectar()
    if conn:
        cursor = conn.cursor()
        # No Oracle, usamos SEQUENCE ou IDENTITY para IDs autoincrementais
        try:
            cursor.execute('''
                CREATE TABLE jogadores (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR2(100) NOT NULL,
                    idade NUMBER NOT NULL,
                    posicao VARCHAR2(50) NOT NULL,
                    time VARCHAR2(100) NOT NULL
                )
            ''')
            conn.commit()
        except oracledb.DatabaseError as e:
            # Ignora erro se a tabela já existir
            if "ORA-00955" not in str(e):
                print(f"Erro ao criar tabela: {e}")
        finally:
            conn.close()

def adicionar_jogador(nome, idade, posicao, time):
    conn = conectar()
    if conn:
        cursor = conn.cursor()
        cursor.execute(
            "INSERT INTO jogadores (nome, idade, posicao, time) VALUES (:1, :2, :3, :4)",
            [nome, idade, posicao, time]
        )
        conn.commit()
        conn.close()
        print(f"\n✅ {nome} cadastrado no Oracle!")

def listar_jogadores():
    conn = conectar()
    if conn:
        cursor = conn.cursor()
        cursor.execute("SELECT id, nome, idade, posicao, time FROM jogadores ORDER BY id")
        jogadores = cursor.fetchall()
        conn.close()
        
        print("\n--- ELENCO  ---")
        for j in jogadores:
            print(f"ID: {j[0]} | Nome: {j[1]} | Idade: {j[2]} | Posição: {j[3]} | Time: {j[4]}")

def atualizar_time(id_jogador, novo_time):
    conn = conectar()
    if conn:
        cursor = conn.cursor()
        cursor.execute("UPDATE jogadores SET time = :1 WHERE id = :2", [novo_time, id_jogador])
        if cursor.rowcount > 0:
            conn.commit()
            print("\n🔄 Transferência concluída!")
        else:
            print("\n⚠️ Jogador não encontrado.")
        conn.close()

def excluir_jogador(id_jogador):
    conn = conectar()
    if conn:
        cursor = conn.cursor()
        cursor.execute("DELETE FROM jogadores WHERE id = :1", [id_jogador])
        conn.commit()
        conn.close()
        print(f"\n❌ Jogador removido.")

def menu():
    criar_tabela()
    while True:
        print("\n--- CRUD JOGADORES  ---")
        print("1. Cadastrar Jogador")
        print("2. Ver Lista")
        print("3. Mudar Time do Jogador")
        print("4. Remover Jogador")
        print("5. Sair")
        
        op = input("Opção: ")
        if op == '1':
            adicionar_jogador(input("Nome: "), int(input("Idade: ")), input("Posição: "), input("Time: "))
        elif op == '2':
            listar_jogadores()
        elif op == '3':
            atualizar_time(int(input("ID: ")), input("Novo Time: "))
        elif op == '4':
            excluir_jogador(int(input("ID: ")))
        elif op == '5':
            break

if __name__ == "__main__":
    menu()